### PR TITLE
Update dependencies

### LINKED ISSUE #66: Update dependencies

### PR DESCRIPTION
**Pull request by karlmolina**
closes #66

### CODE REVIEW

**Comment by sambehrens** [comment]
I would feel better if this passes tracis-ci before it gets merged because updating dependencies can be risky

**Review by sambehrens — CHANGES_REQUESTED** [review]
I would feel better if this passes travis-ci before it gets merged because updating dependencies can be risky

**Comment by karlmolina** [comment]
test

**Comment by karlmolina** [comment]
> I would feel better if this passes travis-ci before it gets merged because updating dependencies can be risky

Alright travis is up.

**Review by sambehrens — APPROVED** [review]

**Pull request merged**
