### PR TITLE
Restructure APIs and Models

### PR DESCRIPTION
**Pull request by pgiffy**

### CODE REVIEW

**Review by karlmolina — CHANGES_REQUESTED** [review]
Look at my merge request to see how I use the schema validators. And then you don't actually need a lot of the validators inside /validation/ except for special cases like the admin confirm password field. Also you have api tests that are failing. Look at [my commit](https://github.com/dog-house-development/poodl/commit/fc0177d194ae50d450d4dad0c23e21c8a5a966f1) to see how I want to change the api tests so that they actually work. I'm using  [mongo-unit](https://www.toptal.com/nodejs/integration-and-e2e-tests-nodejs-mongodb) instead of mockgoose because that is deprecated.

**Comment by pgiffy** [comment]
I made the changes but it looks like the duplicate error is not triggering, can you check if I missed something.

**Comment by karlmolina** [comment]
> I made the changes but it looks like the duplicate error is not triggering, can you check if I missed something.

You need to add unique to the field in the schema that should not be duplicated, for admin's email it would be like: 
```js
email: {
    type: String,
    unique: true,
    required: [true, 'email field is required']
}
```

this makes me realize that I don't actually have this on activities for the name, and the reason it still works is because there is an index stored in the database see [here](https://mlab.com/databases/poodldev/collections/activities?q=&f=&s=&pageNum=0&pageSize=10#indexes).

**Comment by karlmolina** [comment]
fix your eeror in the pipleeing

**Review by karlmolina — APPROVED** [review]

**Review by sambehrens — APPROVED** [review]

**Pull request merged**
